apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: public-demo
  annotations:
    {}
    #  key: string
  creationTimestamp: '2024-01-11T18:55:02Z'
  generation: 1
  labels:
    {}
    #  key: string
  namespace: fleet-local
spec:
  branch: main
  clientSecretName: gitfleetsshkey
  correctDrift:
    enabled: true
#    force: boolean
#    keepFailHistory: boolean
  insecureSkipTLSVerify: false
  paths:
#    - string
  repo: 'ssh://git@github.com:therealcreynold/public_demo.git'
  targets:
    - clusterSelector:
        matchExpressions:
          - key: provider.cattle.io
            operator: NotIn
            values:
              - harvester
#    - clusterGroup: string
#      clusterGroupSelector:
#        matchExpressions:
#          - key: string
#            operator: string
#            values:
#              - string
#        matchLabels:  key: string
#      clusterName: string
#      clusterSelector:
#        matchExpressions:
#          - key: string
#            operator: string
#            values:
#              - string
#        matchLabels:  key: string
#      name: string
#  caBundle: string
#  forceSyncGeneration: int
#  helmRepoURLRegex: string
#  helmSecretName: string
#  helmSecretNameForPaths: string
#  imageScanCommit:
#    authorEmail: string
#    authorName: string
#    messageTemplate: string
#  imageScanInterval: string
#  keepResources: boolean
#  paused: boolean
#  pollingInterval: string
#  revision: string
#  serviceAccount: string
#  targetNamespace: string
__clone: true