image:
  cisoperator:
    repository: harbor.edge.rancher.lol/rancher/cis-operator
    tag: v1.0.10
  securityScan:
    repository: harbor.edge.rancher.lol/rancher/security-scan
    tag: v0.2.9
  sonobuoy:
    repository: harbor.edge.rancher.lol/rancher/mirrored-sonobuoy-sonobuoy
    tag: v0.56.7

global:
  kubectl:
    repository: harbor.edge.rancher.lol/rancher/kubectl
    tag: v1.20.2

