test_pod:
  image: bats/bats:v1.1.0
  pullPolicy: IfNotPresent

loki:
  enabled: true
  isDefault: true
  persistence:
    enabled: true
    storageClassName: longhorn
    size: 5Gi

  ingress:
    enabled: false
    hosts:
    - host: loki.aws.rancher.lol
      paths:
      - /

promtail:
  enabled: false
