apiVersion: neuvector.com/v1
kind: NvAdmissionControlSecurityRule
metadata:
  name: fleet-default
spec:
  config:
    client_mode: service
    enable: true
    mode: protect
  rules:
  - action: deny
    comment: nginx default namespace
    criteria:
    - name: image
      op: containsAny
      path: image
      value: library/nginx
    - name: namespace
      op: containsAny
      path: namespace
      value: default