---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dvwa
  labels:
    app: dvwa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dvwa
  template:
    metadata:
      labels:
        app: dvwa
    spec:
      containers:
      - name: demo
        image: brooksphilip/neuvector-dvwa
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: dvwa
spec:
  selector:
    app: dvwa
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
