---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: brooksphilip@mac.com
    server: https://acme-v02.api.letsencrypt.org/directory
    preferredChain: "DST Root CA X3"
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - dns01:
        cloudflare:
          email: brooksphilip@mac.com
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token