apiVersion: v1
items:
- apiVersion: neuvector.com/v1
  kind: NvSecurityRule
  metadata:
    name: nv.nmap.default
    namespace: default
  spec:
    dlp:
      settings: []
      status: true
    egress:
    file: []
    ingress: []
    process:
    - action: allow
      allow_update: false
      name: pause
      path: /pause
    process_profile:
      baseline: basic
    target:
      policymode: Monitor
      selector:
        comment: ""
        criteria:
        - key: service
          op: =
          value: nmap.default
        - key: domain
          op: =
          value: default
        name: nv.nmap.default
        original_name: ""
    waf:
      settings: []
      status: true
kind: List
metadata: null
