cloudprovider: vsphere
cloudCredentialSecretName: cattle-global-data:cc-gtxkt
cluster:
  annotations: {}
  labels:
    environment: bigbang
    location: homelab
    carbide-public: true
    airgapdocs: true
  name: fleet-vsphere
kubernetesVersion: v1.24.16+rke2r1
cni: canal
system_default_registry: rgcrprod.azurecr.us
registries:
  configs:
    rgcrprod.azurecr.us:
      authConfigSecretName: registryconfig-auth-m4zwc
      caBundle: ''
      insecureSkipVerify: false
vcenter:
  host: "192.168.1.111"
  skip_tls_verify: true
  datacenters: "HomeLab"
  username: Administrator@vsphere.local
  password: 'Typhoonss1!'

monitoring:
  enabled: false

# STIG-compliance settings
profile: cis-1.6
selinux: true
secrets_encryption: true
protect_kernel_defaults: true
write_kubeconfig_mode: "0640"
use_service_account_credentials: true
kube_apiserver_arg: 
- tls-min-version=VersionTLS12
- tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
- authorization-mode=RBAC,Node
- anonymous-auth=false
- audit-policy-file=/etc/rancher/rke2/audit-policy.yaml
- audit-log-mode=blocking-strict
- audit-log-maxage=30
kube_scheduler_arg:
- tls-min-version=VersionTLS12
- tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
kube_controller_manager_arg:
- bind-address=127.0.0.1
- use-service-account-credentials=true
- tls-min-version=VersionTLS12
- tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
kubelet_arg:
- protect-kernel-defaults=true
- read-only-port=0
- authorization-mode=Webhook
- streaming-connection-idle-timeout=5m

# Specify nodepool options. Can add multiple node groups, specify etcd, controlplane and worker roles.
nodepools:
- name: control-vsphere
  etcd: true
  controlplane: true
  worker: false

  labels: {}
  taints: {}
  quantity: 1
  paused: false

  # vm template to clone (referenced in content-libraruy)
  cloneFrom: "UbuntuTemplate"

  # Filepath to a cloud-config yaml file to put into the ISO user-data
  cloudConfig: |-
    #cloud-config
    write_files:
    - path: /etc/sysctl.d/60-rke2-cis.conf
      owner: root
      content: |
        vm.panic_on_oom=0
        vm.overcommit_memory=1
        kernel.panic=10
        kernel.panic_on_oops=1
    runcmd:
    - useradd -r -c "etcd user" -s /sbin/nologin -M etcd -U
    - systemctl restart systemd-sysctl

  cpuCount: "4"
  diskSize: "20000"
  memorySize: "4096"
  creationType: "template"

  # # If you choose to clone from a content library template specify the name of the library
  # contentLibrary: "cl"

  # vSphere datacenter for virtual machine
  datacenter: "/HomeLab"

  # vSphere datastore for virtual machine
  datastore: "/HomeLab/datastore/Synology"

  # vSphere folder. This folder must already exist in the datacenter
  folder: "/HomeLab/vm/Rancher"

  # vSphere networks where the virtual machine will be attached
  network: 
  - "/HomeLab/network/Server Network"

  # vSphere resource pool
  pool: "/HomeLab/host/Cluster1/Resources"

  # If using a non-B2D image you can specify the ssh port
  sshPort: "22"

  sshUser: ubuntu
  # If using a non-B2D image the uploaded keys will need chown'ed, defaults to staff e.g. docker:staff
  sshUserGroup: staff

  vcenterPort: 443
- name: worker-vsphere
  etcd: false
  controlplane: false
  worker: true

  labels: {}
  taints: {}
  quantity: 2
  paused: false

  # If you choose creation type clone a name of what you want to clone is required
  cloneFrom: "UbuntuTemplate"

  # Filepath to a cloud-config yaml file to put into the ISO user-data
  cloudConfig: |-
    #cloud-config
    write_files:
    - path: /etc/sysctl.d/60-rke2-cis.conf
      owner: root
      content: |
        vm.panic_on_oom=0
        vm.overcommit_memory=1
        kernel.panic=10
        kernel.panic_on_oops=1
    runcmd:
    - systemctl restart systemd-sysctl

  cpuCount: "4"
  memorySize: "4096"
  diskSize: "20000"
  creationType: "template"

  # # If you choose to clone from a content library template specify the name of the library
  # contentLibrary: "cl"

  # vSphere datacenter for virtual machine
  datacenter: "/HomeLab"

  # vSphere datastore for virtual machine
  datastore: "/HomeLab/datastore/Synology"

  # vSphere folder. This folder must already exist in the datacenter
  folder: "/HomeLab/vm/Rancher"

  # vSphere networks where the virtual machine will be attached
  network: 
  - "/HomeLab/network/Server Network"

  # vSphere resource pool
  pool: "/HomeLab/host/Cluster1/Resources"

  # If using a non-B2D image you can specify the ssh port
  sshPort: "22"

  sshUser: ubuntu
  # If using a non-B2D image the uploaded keys will need chown'ed, defaults to staff e.g. docker:staff
  sshUserGroup: staff

  vcenterPort: 443