kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: airgapdocs
  namespace: fleet-default
spec:
  repo: git@github.com:brooksphilip/public_demo.git
  branch: main
  clientSecretName: auth-27sb9

  # To target specific clusters, uncomment this block
  targets:
  - clusterGroup: carbide-public
  - clusterSelector:
      matchLabels:
        airgapdocs: deploy

  paths:
  - "./airgapped-docs"