kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: carbide-public
  namespace: fleet-default
spec:
  repo: git@github.com:therealcreynold/public_demo.git
  branch: main
  clientSecretName: gitfleetsshkey

  # To target specific clusters, uncomment this block
  targets:
  - clusterGroup: carbide-public
  - clusterSelector:
      matchLabels:
        carbide-public: "true"


  paths:
  - "./carbide"