apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: clusters
  namespace: fleet-local
spec:
  branch: main
  clientSecretName: gitfleetsshkey
  insecureSkipTLSVerify: false
  paths:
    - clusters
  repo: git@github.com:therealcreynold/public_demo.git
  targets:
    - clusterSelector:
        matchExpressions:
          - key: provider.cattle.io
            operator: NotIn
            values:
              - harvester
