apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: logging
  namespace: fleet-default
spec:
  branch: main
  clientSecretName: gitfleetsshkey
  paths:
    - gitops/logging
  repo: git@github.com:therealcreynold/public_demo.git
  targets:
  - clusterSelector:
      matchLabels:
        logging: "true"